baseURL = 'https://academic.panda2134.site/'
languageCode = 'en-us'
title = 'Jiangyi Liu'
theme = ["PaperMod"]
mainsections = ["posts"]

[outputs]

home = ['HTML', 'RSS', 'JSON']

[params.homeInfoParams]
imageUrl = "images/selfie.png"
imageHeight = 174
imageWidth = 120
Title = "Hi there 👋"
Content = """
I'm a PhD student at University of Wisconsin - Madison, mainly studying programming languages, including formal verification and program synthesis.

In the past, I had the opportunity to be advised by [Prof. Loris D'Antoni](https://cseweb.ucsd.edu/~ldantoni/) who is very energetic at doing research.
I'm currently working with [Prof. Tej Chajed](https://www.chajed.io) on file system verification.

When I don't do research, I mess up with [amateur radio](https://en.wikipedia.org/wiki/Amateur_radio), play video games (while also [*modding*](https://en.wikipedia.org/wiki/Video_game_modding) them), and watch animes.
"""

[[menu.main]]

identifier = 'cv-pdf'
name = 'CV'
url = 'https://github.com/panda2134/cv-academic/releases/download/latest/main.pdf'
weight = 10

[[menu.main]]

identifier = 'orcid-page'
name = 'ORCID'
url = 'https://orcid.org/0000-0001-6525-4659'
weight = 20
